---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Data visualization and analytics
    gethomepage.dev/group: Cluster Management.Monitoring
    gethomepage.dev/icon: grafana.png 
    gethomepage.dev/name: Grafana
    gethomepage.dev/pod-selector: ""
spec:
  rules:
    - host: grafana.k8s.local.guatalupe.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 80
  tls:
    - hosts:
        - grafana.k8s.local.guatalupe.com
      secretName: grafana-web-ui-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Metric collection system
    gethomepage.dev/group: Cluster Management.Monitoring
    gethomepage.dev/icon: prometheus.png 
    gethomepage.dev/name: Prometheus
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/widget.type: prometheus
    gethomepage.dev/widget.url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
spec:
  rules:
    - host: prometheus.k8s.local.guatalupe.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-prometheus
                port:
                  number: 9090
  tls:
    - hosts:
        - prometheus.k8s.local.guatalupe.com
      secretName: prometheus-web-ui-tls

