apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  releaseName: promtail
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.15.5 # choose a stable version
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    config:
      clients:
        - url: http://loki.monitoring:3100/loki/api/v1/push
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

