apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true
    traefik: true
  settings.yaml: |
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system.svc.cluster.local
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - DNS:
        - Pihole:
            href: https://pihole.local.guatalupe.com/admin
            icon: sh-pi-hole.png
            description: Pihole DNS
            widgets:
              - type: pihole
                url: https://pihole.local.guatalupe.com
                version: 6
                key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}

    - Media:
        - Plex:
            href: https://plex.local.guatalupe.com
            icon: sh-plex.png
            description: Plex media server
            widgets:
              - type: plex
                url: https://plex.local.guatalupe.com
                key: {{HOMEPAGE_VAR_PLEX_TOKEN}}

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true
  docker.yaml: ""