apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
    creationPolicy: Owner
  data:
  - secretKey: pihole-api-key
    remoteRef:
      key: pihole-api-key
  - secretKey: plex-device-token
    remoteRef:
      key: plex-device-token
  - secretKey: grafana-admin-user
    remoteRef:
      key: grafana-admin-user
  - secretKey: grafana-admin-password
    remoteRef:
      key: grafana-admin-password