apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - repository.yaml
  - secrets.yaml
  - release.yaml
  - env.yaml

configurations:
  - kustomizeconfig.yaml