apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  install:
    timeout: 10m
    crds: Create
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "77.1.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 12h
  values:
    kubeControllerManager:
      service:
        selector:
          k8s-app: kube-controller-manager
    kubeScheduler:
      service:
        selector:
          k8s-app: kube-scheduler
    kubeEtcd:
      enabled: true
      service:
        enabled: true
        port: 2381
        targetPort: 2381
      serviceMonitor:
        enabled: true
        scheme: http
        interval: 5m
        scrapeTimeout: 10s
        honorLabels: true
        metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'etcd_(server_has_leader|server_leader_changes_seen_total|disk_backend_commit_duration_seconds|network_peer_round_trip_time_seconds|server_proposals_failed_total|server_proposals_pending|server_proposals_committed_total)'
          action: keep

    alertmanager:
      enabled: false

    prometheus:
      prometheusSpec:
        podMonitorNamespaceSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring

        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false

    grafana:
      grafana.ini:
        server: 
          serve_from_sub_path: false
          protocol: http 
          port: 3000
        date_formats:
          default_week_start: monday

      envFromSecret: grafana-env

      admin:
        existingSecret: grafana-ui-credentials
        userKey: admin-user
        passwordKey: admin-password

      persistence:
        enabled: true
        type: pvc
        accessModes:
          - ReadWriteOnce
        size: 5Gi
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule