apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "76.3.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 12h
  values:
    kubeControllerManager:
      service:
        selector:
          k8s-app: kube-controller-manager
    kubeScheduler:
      service:
        selector:
          k8s-app: kube-scheduler

    alertmanager:
      enabled: false

    prometheus:
      prometheusSpec:
        podMonitorNamespaceSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring

        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false

    grafana:
      grafana.ini:
        server: 
          serve_from_sub_path: false
          protocol: http 
          port: 3000
        date_formats:
          default_week_start: monday

      envFromSecret: grafana-env

      admin:
        exisitingSecret: grafana-ui-credentials
        userKey: admin-user
        passwordKey: admin-password

      persistence:
        enabled: true
        type: pvc
        accessModes:
          - ReadWriteOnce
        size: 5Gi
        lookupVolumeName: true


  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule